# Generated by Django 3.2.16 on 2025-01-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
