# Generated by Django 3.2.16 on 2025-01-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20250125_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Инградиент', 'verbose_name_plural': 'Инградиенты'},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
